INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME,PHONE_NUMBER,USER_EMAIL_ID,USER_PASSWORD,USER_TYPE,USER_STATUS_ACTIVE,USER_IMAGE) VALUES(100,'VISHWANATH','636244823','VISHWANATHDALAWAI@GMAIL.COM','QAZ','ADMIN','YES','NULL');

insert into product(PRODUCTID, PRODUCT_CATEGORY_NAME,PRODUCT_NAME,PRODUCT_DESCRIPTION,STARTING_BID_PRICE,APPROVALSTATUS,REPORTFLAG,INCREMENTPRICE,PRODUCTBOUGTHYEAR,PRODUCTMODEL,CUSTOMER) VALUES(100,'CAR','BIKE','NICE',12000,'YES','NO',10000,'2108','XS',100);

